### ISSUE TITLE
T1 Data

### ISSUE THREAD

**Issue by Rubines** [LadyRoninEngineer/Si473x#1]
Hi

I want to build your MULTI-BAND RADIO WITH FILTER, thank you for sharing but I found no data for the T1 Balun.
How many turns are needed ?

Cheers
Michael

**Comment by LadyRoninEngineer** [comment]
Michael -
Apologies that I committed that info:

Core: BN43-2402 binocular core
4 turns of triflar 30AWG enameled wire (three (3) lengths ~7"/18cm)
2 pairs of wire are the primary
1 wire is the secondary

Obvious perhaps, but it is important to keep track of the wires - a set of Sharpie marks will assist on either end of the wire.

![Transformer](https://user-images.githubusercontent.com/74212539/225433953-7732933b-6316-41f5-b596-799e2b3105c8.jpg)
